// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixllzixjlcxgpqptabde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4bGx6aXhqbGN4Z3BxcHRhYmRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjY4ODgsImV4cCI6MjA2MzY0Mjg4OH0.1ISugIiGMvpjcO3rXsB93CCWkURMzPnFI_YB6zFtXDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);